Repository ProcessMaker/screen-builder, pull requests merged in 2024-09, with the labels that each got.

#1685 FOUR-16700: XSS via PDF File Upload (for 4.10.2)
  src/components/renderer/file-upload.vue
Labels: 4.10.2+patch-ellucian

#1688 FOUR-18988: Display message if file upload fails (for 4.10.2)
  src/components/renderer/file-upload.vue
Labels: 4.10.2+patch-ellucian

#1692 FOUR-19008: Browser's alerts are displayed when a `Dangerous PDF file` is uploaded and submit button is interrupted (for 4.10.2)
  src/components/renderer/file-upload.vue
Labels: 4.10.2+patch-ellucian

#1689 FOUR-18984 Parallel Task is not redirected according element destination configuration once completed
  src/components/task.vue
Labels: 4.11.2

#1684 FOUR-16700: XSS via PDF File Upload
  src/components/renderer/file-upload.vue
Labels: 4.11.2

#1699 FOUR-19102 Fix Redirect when the process ends before load the request
  src/components/task.vue
Labels: 4.11.2

#1716 FOUR-19110: [40531] changes on screen are not reflected in ongoing cases
  src/DataProvider.js
  src/components/task.vue
Labels: 4.11.4

#1718 [40754] Links added to a Display screen set as a "screen for completed" in Web entries are not working
  src/components/task.vue
Labels: 4.11.4
