Repository ProcessMaker/screen-builder, pull requests merged in 2024-10, with the labels that each got.

#1728 Set self-service property on mounted
  src/components/task.vue
Labels: 4.11.5

#1734 Feature/FOUR-18116: STORY Add Collection View Control in Display Screens
  src/components/index.js
  src/components/inspector/collection-records-list.vue
  src/components/renderer/form-collection-view-control.vue
  src/components/renderer/index.js
  src/form-builder-controls.js
Labels: 4.12.0

#1719 FOUR-16701: Unrestricted File Upload
  src/components/renderer/file-upload.vue
Labels: 4.11.6

#1720 FOUR-14970 Replace regex with dot_notation validator
  src/form-control-common-properties.js
  tests/e2e/specs/Builder.spec.js
Labels: 4.11.6
