Repository ProcessMaker/screen-builder, pull requests merged in 2025-07, with the labels that each got.

#1832 FOUR-25240:Implement property linkDisplayStyle = [LINK, BUTTON]
  src/components/accordions.js
  src/components/index.js
  src/components/renderer/link-button.vue
  src/form-builder-controls.js
  src/form-control-common-properties.js
Labels: merge-story

#1834 task/FOUR-25270-fix: Fixing mustache syntax variables in values with spaces
  src/components/renderer/form-record-list.vue
Labels: Beta3, 4.15.4

#1836 FOUR-25227: [STORY] Update Email Notifications Default Template
  src/components/accordions.js
  src/components/index.js
  src/components/renderer/link-button.vue
  src/form-builder-controls.js
  src/form-control-common-properties.js
Labels: merge-epic

#1838 ENG-54 Add Click Handler to Buttons
  .gitignore
  .storybook/main.js
  src/components/inspector/button/handler-event-property.js
  src/components/inspector/code-editor.vue
  src/components/inspector/index.js
  src/components/renderer/form-button.vue
  src/components/vue-form-builder.vue
  src/form-builder-controls.js
  src/mixins/DataReference.js
  src/mixins/extensions/LoadFieldComponents.js
  src/stories/CodeEditor.stories.js
  tests/e2e/fixtures/button_click_handler.json
  tests/e2e/specs/ButtonClickHandler.spec.js
Labels: Beta1, 4.15.5
