Repository ProcessMaker/screen-builder, pull requests merged in 2025-02, with the labels that each got.

#1787 FOUR-21685: The value set in the aria label field of the select list disappears after refreshing the page
  src/components/inspector/options-list.vue
  src/form-builder-controls.js
Labels: 4.13.0, RC2

#1788 FOUR-21691:The values set by calcs in a select list(drop-down) lost after refresh the page
  src/components/inspector/options-list.vue
  tests/e2e/specs/FormSelectList.spec.js
Labels: 4.13.0, RC2

#1790 FOUR-21710:The options in the select list disappears to record list with collection configured
  src/components/inspector/collection-data-source.vue
  src/components/inspector/column-setup.vue
Labels: 4.13.0, RC4

#1795 FOUR-22021: Default variables are not displayed on a screen when using a language other than English
  src/components/vue-form-builder.vue
  src/main.js
Labels: RC2, 4.13.2

#1792 Cannot create a pmblock with the language translation Português and Na Vosa Vakaviti (Fijian)
  src/App.vue
  src/components/vue-form-builder.vue
Labels: RC1, 4.13.2

#1791 Aria label field disappears of the Radio check box as field
  src/components/inspector/options-list.vue
Labels: RC1, 4.13.2

#1793 FOUR-21952 : "This content does not exist. We could not locate indicated data" alert error appears in Collection record control even though the id exists
  src/components/inspector/collection-display-mode.vue
  src/components/renderer/form-collection-record-control.vue
  src/form-builder-controls.js
Labels: RC1, 4.13.2

#1782 FOUR-19561: In a screen with more than one page, when I zoom more than 150% I return to the first page
  src/mixins/DeviceDetector.js
Labels: RC1, 4.14.0
