Repository ProcessMaker/screen-builder, pull requests merged in 2025-03, with the labels that each got.

#1798 FOUR-22168 collection record control settings are copied when selection is inserted
  src/components/inspector/collection-display-mode.vue
  src/components/inspector/collection-records-list.vue
Labels: RC2, 4.13.2

#1797 FOUR-22166 Collection Record ID is not visible in preview screen
  src/components/renderer/form-collection-record-control.vue
Labels: RC2, 4.13.2

#1789 FOUR-21660: The form screen is shown as conversational when we start a new case
  src/components/task.vue
Labels: 4.14.0, Alpha3

#1800 FOUR-21685: The value set in the aria label field of the select list …
  src/components/inspector/options-list.vue
Labels: 4.14.0, Alpha3

#1802 bugfix/FOUR-22187 Fields in a Select list type collection are corrupted after changing its Data source
  src/components/inspector/options-list.vue
Labels: 4.14.0, Alpha3

#1804 FOUR-22880: After reload page, remove button is not present in copied…
  src/components/vue-form-builder.vue
  tests/e2e/specs/ClipboardTestCases.spec.js
Labels: 4.14.0

#1808 FOUR-22882: Duplicate controls in the Clipboard page doesn't work
  src/components/vue-form-builder.vue
  tests/e2e/specs/ClipboardTabDuplicate.spec.js
Labels: 4.14.0
