Repository ProcessMaker/screen-builder, pull requests merged in 2025-08, with the labels that each got.

#1816 FOUR-22605: [SUMMER 25]: Participant Home Screen V2
  src/components/index.js
  src/components/renderer/case-progress-bar.vue
  src/components/renderer/index.js
  src/form-builder-controls.js
  tests/e2e/specs/FOUR6788_ScreenPerformanceTests.spec.js
Labels: summer-2025, version-tbd

#1841 FOUR-25223: [EPIC] Email Notifications update.
  src/components/accordions.js
  src/components/index.js
  src/components/renderer/link-button.vue
  src/form-builder-controls.js
  src/form-control-common-properties.js
Labels: spring-2025, 4.15.6

#1839 FOUR-25305 There are console errors in loop with Rich text inside in Manual Task
  src/components/vue-form-builder.vue
  tests/e2e/specs/SelectListDependentCollection.spec.js
Labels: failing, version-tbd

#1853 FOUR-25821:Link URL has additional property in Design, which causes values to be lost with old screens
  src/components/renderer/link-button.vue
Labels: 4.15.6, Beta4

#1854 FOUR-25814: Preview screen is empty when dynamic Panel is created
  src/form-builder-controls.js
  src/mixins/extensions/FormDynamicPanel.js
  tests/e2e/fixtures/dynamic_panel_empty.json
  tests/e2e/specs/DynamicPanelEmpty.spec.js
Labels: 4.15.6
